version: '3'
services:
  MensaHub-Junction:
    image: olech2412/mensahub-junction:latest
    ports:
      - "8082:8082"
    volumes:
      - /home/christopho/mensaHub:/root/mensaHub
    environment:
      - encryption.key=S5o3qev2RKxYWNjhXSpuzkmwF3ZqvM!E
    networks:
      - mensaHub_network

networks:
  mensaHub_network:
    external: true