version: '3.8'

services:
  app:
    build: .
    ports:
      - "8084:8084"
    environment:
      - FLASK_ENV=production
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=host.docker.internal
      - DB_NAME=mensaHub