version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/christopho/Workspace/Coding/IntelliJ/EssensGetter API/addons/collaborative_filtering/:/mnt/data
    environment:
      - FLASK_ENV=production
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=mariadb
      - DB_NAME=mensaHub