version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=mariadb
      - DB_NAME=mensaHub