name: Build-Pipeline-And-Deploy

on:
  workflow_dispatch:
    inputs:
      version-mensahub-models:
        description: 'Version of models package to deploy'
        required: true

jobs:

  build-mensahub-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Models
        run: |
          cd MensaHub-Models
          mvn clean install

  build-mensahub-gateway:
    runs-on: ubuntu-latest
    needs: build-mensahub-models
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Gateway
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-Gateway'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

  build-mensahub-junction:
    runs-on: ubuntu-latest
    needs: build-mensahub-models

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Junction
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-Junction'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

  build-mensahub-data-dispatcher:
    runs-on: ubuntu-latest
    needs: build-mensahub-models

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-DataDispatcher
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-DataDispatcher'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

  publish-mensahub-models:
    runs-on: ubuntu-latest
    needs: [build-mensahub-models, build-mensahub-data-dispatcher, build-mensahub-junction, build-mensahub-gateway]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
            persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT }}
        run: |
          cd MensaHub-Models
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mvn versions:set -DnewVersion=${{ github.event.inputs.version-mensahub-models }}
          mvn versions:commit
          git add pom.xml
          git commit -m "Update version automated from GitHub action to ${{ github.event.inputs.version-mensahub-models }}"
          git push https://x-access-token:${{ secrets.DEPLOYMENT }}@github.com/${{ github.repository }} HEAD:refs/heads/master

      - name: Build and Publish MensaHub-Models
        run: |
          cd MensaHub-Models
          mvn --batch-mode deploy -Dmaven.version=${{ github.event.inputs.version-mensahub-models }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PACKAGE }}
