name: Build-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-mensahub-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Models
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-Models'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}
          
  build-mensahub-gateway:
    runs-on: ubuntu-latest
    needs: build-mensahub-models

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Gateway
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-Gateway'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

  build-mensahub-junction:
    runs-on: ubuntu-latest
    needs: build-mensahub-gateway

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Junction
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-Junction'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

  build-mensahub-data-dispatcher:
    runs-on: ubuntu-latest
    needs: build-mensahub-junction

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-DataDispatcher
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-DataDispatcher'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}
