name: Build-Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Install Google Java Format
        run: |
          sudo apt-get update
          sudo apt-get install -y google-java-format

      - name: Run Prettier for HTML and CSS
        run: prettier --write "**/*.{html,css}"

      - name: Run Google Java Format
        run: |
          find . -name "*.java" | xargs google-java-format -i

  build-mensahub-models:
    runs-on: ubuntu-latest
    needs: format-code
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
  
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
  
      - name: Build MensaHub-Models
        run: |
          cd MensaHub-Models
          mvn clean install

  build-mensahub-gateway:
    runs-on: ubuntu-latest
    needs: build-mensahub-models

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Gateway
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-Gateway'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

  build-mensahub-junction:
    runs-on: ubuntu-latest
    needs: build-mensahub-gateway

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-Junction
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-Junction'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

  build-mensahub-data-dispatcher:
    runs-on: ubuntu-latest
    needs: build-mensahub-junction

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MensaHub-DataDispatcher
        run: 'mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean install -pl MensaHub-DataDispatcher'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}
