name: Code formatting

on:
  workflow_dispatch:

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
