name: Build and Publish MensaHub-Models

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build MensaHub-Models
      run: mvn -f MensaHub-Models clean install

    - name: Publish JAR to GitHub Packages
      run: |
        echo "//registry.npmjs.org/:_authToken=\${{ secrets.MY_SECRETS }}" > ~/.npmrc
        mvn -f MensaHub-Models deploy
