name: Spring Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Start MariaDB Container
        run: |
          docker run -d -p 3306:3306 --name mariadb -e MYSQL_ROOT_PASSWORD=your_password -e MYSQL_DATABASE=your_database mariadb:latest

      - name: Wait for MariaDB to Start
        run: |
          sleep 15

      - name: Run Tests with Docker
        run: |
          docker run --network host -v $PWD:/usr/src/app -w /usr/src/app --rm maven:3.8.1-openjdk-11 mvn test

      - name: Stop MariaDB Container
        run: docker stop mariadb
