name: Test CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  testAPI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test MensaHub-Gateway
        run: 'cd MensaHub-Gateway && mvn -s $GITHUB_WORKSPACE/.github/config/maven-settings.xml -Dpackage.publicKey=$PACKAGE_READ clean test'
        env:
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}

      - name: Generate Test Report
        run: mvn surefire-report:report

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: target/site/surefire-report.html