name: Test CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  testAPI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "github",
                "username": "olech2412",
                "password": "${env.PACKAGE_KEY_READ}",
              }
            ]

      - name: Display settings.xml
        run: cat $HOME/.m2/settings.xml

      - name: Build and Test MensaHub-Gateway
        run: 'cd MensaHub-Gateway && mvn clean test'

      - name: Generate Test Report
        run: mvn surefire-report:report

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: target/site/surefire-report.html
